import sys
from PyQt5 import QtWidgets,QtGui
from PyQt5 import QtGui
from thankyou import Thank_you
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtWidgets import (QLabel, QRadioButton, QPushButton, QVBoxLayout, QApplication, QWidget)

"""This class consists of different restaurants method. Also we have defined calculation method for the order given by customers."""

class Restaurant(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()

    def Student_Biryani(self,QtWidgets,QtGui):

        self.w = QtWidgets.QWidget()

        #Buttons defined
        self.Proceed=QtWidgets.QPushButton(self.w)
        self.Clear=QtWidgets.QPushButton(self.w)
        self.Cal=QtWidgets.QPushButton(self.w)

        #Labels defined
        self.Lc=QtWidgets.QLabel(self.w)
        self.Lb=QtWidgets.QLabel(self.w)
        self.Lf=QtWidgets.QLabel(self.w)
        self.Lp=QtWidgets.QLabel(self.w)
        self.Lname=QtWidgets.QLabel(self.w)
        self.Lmen=QtWidgets.QLabel(self.w)
        self.total=QtWidgets.QLabel(self.w)
        self.quantity=QtWidgets.QLabel(self.w)
        self.Calc=QtWidgets.QLabel(self.w)
        self.Calb=QtWidgets.QLabel(self.w)
        self.Calf=QtWidgets.QLabel(self.w)
        self.Calp=QtWidgets.QLabel(self.w)
        self.ATotal=QtWidgets.QLabel(self.w)
        self.CalATotal=QtWidgets.QLabel(self.w)

        #LineEdits defined
        self.Lc2=QtWidgets.QLineEdit(self.w)
        self.Lb2=QtWidgets.QLineEdit(self.w)
        self.Lf2=QtWidgets.QLineEdit(self.w)
        self.Lp2=QtWidgets.QLineEdit(self.w)

        #Labels set TEXT
        self.Lname.setText('MENU')
        self.Lmen.setText('Items')
        self.Lc.setText('Chicken Tikka')
        self.Lb.setText('Beef Biryani')
        self.Lf.setText('Fish Biryani')
        self.Lp.setText('Prawn Biryani')

        #Buttons set TEXT
        self.Proceed.setText('Proceed')
        self.Clear.setText('Clear')
        self.Cal.setText('Calculate')
        self.Calc.setText('             ')
        self.Calb.setText('              ')
        self.Calf.setText('               ')
        self.Calp.setText('            ')
        self.CalATotal.setText('               ')

        #Labels set TEXT
        self.total.setText('Price')
        self.quantity.setText('Quantity')
        self.ATotal.setText('Final Total: ')
        
        #font size of TEXT
        textfont=QFont("Impact", 26)
        self.Lname.setFont(textfont)
        textfont=QFont("Times", 20)
        self.Lmen.setFont(textfont)
        textfont=QFont("Times", 20)
        self.total.setFont(textfont)
        self.quantity.setFont(textfont)
        self.ATotal.setFont(textfont)
        self.CalATotal.setFont(textfont)
        textfont=QFont("Calibri", 15)
        self.Lc.setFont(textfont)
        self.Lb.setFont(textfont)
        self.Lf.setFont(textfont)
        self.Lp.setFont(textfont)
        self.Calc.setFont(textfont)
        self.Calb.setFont(textfont)
        self.Calf.setFont(textfont)
        self.Calp.setFont(textfont)

        #Allignment of labels and buttons
        self.Lname.move(590,0)
        self.Lmen.move(420,100)
        self.Lc.move(410,150)
        self.Lb.move(410,200)
        self.Lf.move(410,250)
        self.Lp.move(410,300)
        self.Lc2.move(550,150)
        self.Lb2.move(550,200)
        self.Lf2.move(550,250)
        self.Lp2.move(550,300)
        self.Proceed.move(410,350)
        self.Clear.move(460,375)
        self.Cal.move(510,350)
        self.quantity.move(550,100)
        self.total.move(710,100)
        self.Calc.move(710,148)
        self.Calb.move(710,198)
        self.Calf.move(710,248)
        self.Calp.move(710,298)
        self.CalATotal.move(760,345)
        self.ATotal.move(610,345)
        self.pic=QtWidgets.QLabel(self.w)
        self.pic.setPixmap(QtGui.QPixmap('000001580_Student-Biryani'))

        #button click for buttons
        self.Cal.clicked.connect(self.Calculation_sb)
        self.Clear.clicked.connect(self.Clearing_sb)
        self.Proceed.clicked.connect(self.proceed)
        self.w.setGeometry(290,150,890,400)
        self.w.setWindowTitle('Student Biryani')
        self.w.show()

        
    #This method shows the calculation     
    def Calculation_sb(self):
        try:
            a=self.Lc2.text()
            b=self.Lb2.text()
            c=self.Lf2.text()
            d=self.Lp2.text()
            if a=='' or b=='' or c=='' or d=='':
                raise Exception("Empty Field")
            else:
                q1 =self.Lc2.text()
                int1= int(q1)*(150)
                self.Calc.setText('Rs'+str(int1))
                q2 =self.Lb2.text()
                int2= int(q2)*(180)
                self.Calb.setText('Rs'+str(int2))
                q3 =self.Lf2.text()
                int3= int(q3)*(190)
                self.Calf.setText('Rs'+str(int3))
                q4 =self.Lp2.text()
                int4= int(q4)*(200)
                self.Calp.setText('Rs'+str(int4))
                q5=int(int1+int2+int3+int4)
                self.CalATotal.setText('Rs'+str(q5))
        except Exception:
                QMessageBox.question(self, 'Error', " Put 0 in Empty Fields", QMessageBox.Yes | QMessageBox.Yes, QMessageBox.Yes)
                print("Exception Raised")            

    #Method to clear all the line boxes
    def Clearing_sb(self):             
        self.Calc.clear()
        self.Calb.clear()
        self.Calf.clear()
        self.Calp.clear()
        self.Lc2.clear()
        self.Lb2.clear()
        self.Lf2.clear()
        self.Lp2.clear()
        self.CalATotal.clear()
        self.w.show()

    #method to call the thankyou class
    def proceed(self):
        self.tk=Thank_you()
        self.tk.thanks(QtWidgets,QtGui)

    def McDonalds(self,QtWidgets,QtGui):
        self.w = QtWidgets.QWidget()

        #Labels defined
        self.Lname=QtWidgets.QLabel(self.w)
        self.Lmen=QtWidgets.QLabel(self.w)
        self.Lmen2=QtWidgets.QLabel(self.w)
        self.Ltot=QtWidgets.QLabel(self.w)
        self.Ltot2=QtWidgets.QLabel(self.w)
        self.Quantity=QtWidgets.QLabel(self.w)
        self.Quantity2=QtWidgets.QLabel(self.w)
        self.Lb=QtWidgets.QLabel(self.w)
        self.Ld=QtWidgets.QLabel(self.w)
        self.Lc=QtWidgets.QLabel(self.w)
        self.Lf=QtWidgets.QLabel(self.w)
        self.Lq=QtWidgets.QLabel(self.w)
        self.Ls=QtWidgets.QLabel(self.w)
        self.Lch=QtWidgets.QLabel(self.w)

        #Line boxes defined
        self.Lb2=QtWidgets.QLineEdit(self.w)
        self.Ld2=QtWidgets.QLineEdit(self.w)
        self.Lc2=QtWidgets.QLineEdit(self.w)
        self.Lf2=QtWidgets.QLineEdit(self.w)
        self.Lq2=QtWidgets.QLineEdit(self.w)
        self.Ls2=QtWidgets.QLineEdit(self.w)
        self.Lch2=QtWidgets.QLineEdit(self.w)

        #Labels defined
        self.Calb=QtWidgets.QLabel(self.w)
        self.Cald=QtWidgets.QLabel(self.w)
        self.Calc=QtWidgets.QLabel(self.w)
        self.Calf=QtWidgets.QLabel(self.w)
        self.Calq=QtWidgets.QLabel(self.w)
        self.Cals=QtWidgets.QLabel(self.w)
        self.Calch=QtWidgets.QLabel(self.w)

        #Buttons defined
        self.Cal=QtWidgets.QPushButton(self.w)
        self.Proceed=QtWidgets.QPushButton(self.w)
        self.Clear=QtWidgets.QPushButton(self.w)
        self.ATotal=QtWidgets.QLabel(self.w)
        self.CalATotal=QtWidgets.QLabel(self.w)
        self.pic6=QtWidgets.QLabel(self.w)
        self.pic6.setPixmap(QtGui.QPixmap('mcdonalds'))

        #Labels and buttons set TEXT
        self.Lname.setText('MENU')
        self.Lmen.setText('Items')
        self.Lmen2.setText("Items")
        self.Ltot.setText('Price')
        self.Ltot2.setText("Price")
        self.Quantity.setText('Quantity')
        self.Quantity2.setText("Quantity")
        self.Lb.setText('McChicken')
        self.Ld.setText('Big Mac')
        self.Lc.setText('McRoyale')
        self.Lf.setText('McBeef')
        self.Lq.setText('Family Deal')
        self.Ls.setText('Strawberry Shake')
        self.Lch.setText('Chocolate Shake')
        self.ATotal.setText('Final total:')
        self.Cal.setText('Calculation')
        self.Proceed.setText('Proceed')
        self.Clear.setText('Clear')
        self.CalATotal.setText('                             ')
        self.Calb.setText('                               ')
        self.Cald.setText('                               ')
        self.Calc.setText('                               ')
        self.Calf.setText('                               ')
        self.Calq.setText('                               ')
        self.Cals.setText('                               ')
        self.Calch.setText('                               ')        
        
        

        #Font size of text  
        textfont=QFont("Impact", 26)
        self.Lname.setFont(textfont)
        textfont=QFont("Times", 20)
        self.Lmen.setFont(textfont)
        self.Lmen2.setFont(textfont)
        self.Ltot.setFont(textfont)
        self.Ltot2.setFont(textfont)
        self.Quantity.setFont(textfont)
        self.Quantity2.setFont(textfont)
        self.ATotal.setFont(textfont)
        self.CalATotal.setFont(textfont)
        textfont=QFont("Calibri", 15)
        self.Lb.setFont(textfont)
        self.Ld.setFont(textfont)
        self.Lc.setFont(textfont)
        self.Lf.setFont(textfont)
        self.Lq.setFont(textfont)
        self.Ls.setFont(textfont)
        self.Lch.setFont(textfont)        
        self.Calb.setFont(textfont)
        self.Cald.setFont(textfont)
        self.Calc.setFont(textfont)
        self.Calf.setFont(textfont)
        self.Calq.setFont(textfont)
        self.Cals.setFont(textfont)
        self.Calch.setFont(textfont)        
        
        
        #Allignment of labels and buttons
        self.Lname.move(790,0)
        self.Lmen.move(420,100)
        self.Lmen2.move(810,100)
        self.Ltot.move(710,100)
        self.Ltot2.move(1090,100)
        self.Quantity.move(550,100)
        self.Quantity2.move(950,100)
        self.Lb.move(410,150)
        self.Ld.move(410,200)
        self.Lc.move(410,250)
        self.Lf.move(410,300)
        self.Lq.move(800,175)
        self.Ls.move(800,225)
        self.Lch.move(800,275)
        self.Lb2.move(550,150)
        self.Ld2.move(550,200)
        self.Lc2.move(550,250)
        self.Lf2.move(550,300)
        self.Lq2.move(950,175)
        self.Ls2.move(950,225)
        self.Lch2.move(950,275)
        self.Calb.move(710,150)
        self.Cald.move(710,200)
        self.Calc.move(710,250)
        self.Calf.move(710,300)
        self.Calq.move(1090,175)
        self.Cals.move(1090,225)
        self.Calch.move(1090,275)
        self.CalATotal.move(760,345)
        self.ATotal.move(610,345)
        self.Cal.move(510,350)
        self.Proceed.move(410,350)
        self.Clear.move(460,375)

        #Button click for buttons
        self.Cal.clicked.connect(self.Calculation_mc)
        self.Clear.clicked.connect(self.Clearing_mc)
        self.Proceed.clicked.connect(self.proceed_2)
        self.w.setWindowTitle('Mcdonalds')
        self.w.setGeometry(100,150,1200,400)
        self.w.show()

    #defined method for calculation
    def Calculation_mc(self):
        try:
            a=self.Lb2.text()
            b=self.Ld2.text()
            c=self.Lc2.text()
            d=self.Lf2.text()
            e=self.Lq2.text()
            f=self.Ls2.text()
            g=self.Lch2.text()
            if a=='' or b=='' or c=='' or d=='' or f=='' or g=='' or e=='':
                raise Exception("Empty Field")
            else:

                q1 =self.Lb2.text()
                int1= int(q1)*(350)
                self.Calb.setText('Rs'+str(int1))
                q2 =self.Ld2.text()
                int2= int(q2)*(400)
                self.Cald.setText('Rs'+str(int2))
                q3 =self.Lc2.text()
                int3= int(q3)*(250)
                self.Calc.setText('Rs'+str(int3))
                q4 =self.Lf2.text()
                int4= int(q4)*(550)
                self.Calf.setText('Rs'+str(int4))
                q5 =self.Lq2.text()
                int5= int(q5)*(360)
                self.Calq.setText('Rs'+str(int5))
                q6 =self.Ls2.text()
                int6= int(q6)*(200)
                self.Cals.setText('Rs'+str(int6))
                q7 =self.Lch2.text()
                int7= int(q7)*(200)
                self.Calch.setText('Rs'+str(int7))

                q8=int(int1+int2+int3+int4+int5+int6+int7)
                self.CalATotal.setText('Rs'+str(q8))
        except Exception:
                QMessageBox.question(self, 'Error', " Put 0 in Empty Fields", QMessageBox.Yes | QMessageBox.Yes, QMessageBox.Yes)
                print("Exception Raised")            

    #This method will clear all the line boxes   
    def Clearing_mc(self):
        self.Lb2.clear()
        self.Ld2.clear()
        self.Lc2.clear()
        self.Lf2.clear()
        self.Lq2.clear()
        self.Ls2.clear()
        self.Lch2.clear()
        self.Calb.clear()
        self.Cald.clear()
        self.Calc.clear()
        self.Calf.clear()
        self.Calq.clear()
        self.Cals.clear()
        self.Calch.clear()
        self.CalATotal.clear()
        
    #This method will call thankyou class
    def proceed_2(self):
        self.tk=Thank_you()
        self.tk.thanks(QtWidgets,QtGui)

    def burgerlab(self,QtWidgets,QtGui):
        self.w = QtWidgets.QWidget()

        #Labels defined
        self.Lname=QtWidgets.QLabel(self.w)
        self.Lmen=QtWidgets.QLabel(self.w)
        self.Lmen2=QtWidgets.QLabel(self.w)
        self.Ltot=QtWidgets.QLabel(self.w)
        self.Ltot2=QtWidgets.QLabel(self.w)
        self.Quantity=QtWidgets.QLabel(self.w)
        self.Quantity2=QtWidgets.QLabel(self.w)
        self.Lb=QtWidgets.QLabel(self.w)
        self.Ld=QtWidgets.QLabel(self.w)
        self.Lc=QtWidgets.QLabel(self.w)
        self.Lf=QtWidgets.QLabel(self.w)
        self.Lq=QtWidgets.QLabel(self.w)
        self.Ls=QtWidgets.QLabel(self.w)
        self.Lch=QtWidgets.QLabel(self.w)

        #line boxes defined
        self.Lb2=QtWidgets.QLineEdit(self.w)
        self.Ld2=QtWidgets.QLineEdit(self.w)
        self.Lc2=QtWidgets.QLineEdit(self.w)
        self.Lf2=QtWidgets.QLineEdit(self.w)
        self.Lq2=QtWidgets.QLineEdit(self.w)
        self.Ls2=QtWidgets.QLineEdit(self.w)
        self.Lch2=QtWidgets.QLineEdit(self.w)

        #Labels defined
        self.Calb=QtWidgets.QLabel(self.w)
        self.Cald=QtWidgets.QLabel(self.w)
        self.Calc=QtWidgets.QLabel(self.w)
        self.Calf=QtWidgets.QLabel(self.w)
        self.Calq=QtWidgets.QLabel(self.w)
        self.Cals=QtWidgets.QLabel(self.w)
        self.Calch=QtWidgets.QLabel(self.w)

        #Push buttons defined
        self.Cal=QtWidgets.QPushButton(self.w)
        self.Proceed=QtWidgets.QPushButton(self.w)
        self.Clear=QtWidgets.QPushButton(self.w)
        self.ATotal=QtWidgets.QLabel(self.w)
        self.CalATotal=QtWidgets.QLabel(self.w)
        self.pic6=QtWidgets.QLabel(self.w)
        self.pic6.setPixmap(QtGui.QPixmap('burgerlab'))
        
        #set TEXT for labels and buttons
        self.Lname.setText('MENU')
        self.Lmen.setText('Items')
        self.Lmen2.setText("Items")
        self.Ltot.setText('Price')
        self.Ltot2.setText("Price")
        self.Quantity.setText('Quantity')
        self.Quantity2.setText("Quantity")
        self.Lb.setText('The Boss')
        self.Ld.setText('The Doppler')
        self.Lc.setText('Fire House')
        self.Lf.setText('Animal Fries')
        self.Lq.setText('Quadra Reloaded')
        self.Ls.setText('Strawberry Shake')
        self.Lch.setText('Chocolate Shake')
        self.ATotal.setText('Final total:')
        self.Cal.setText('Calculation')
        self.Proceed.setText('Proceed')
        self.Clear.setText('Clear')
        self.CalATotal.setText('                             ')
        self.Calb.setText('                               ')
        self.Cald.setText('                               ')
        self.Calc.setText('                               ')
        self.Calf.setText('                               ')
        self.Calq.setText('                               ')
        self.Cals.setText('                               ')
        self.Calch.setText('                               ')        
        
        #font size for TEXT    
        textfont=QFont("Impact", 26)
        self.Lname.setFont(textfont)
        textfont=QFont("Times", 20)
        self.Lmen.setFont(textfont)
        self.Lmen2.setFont(textfont)
        self.Ltot.setFont(textfont)
        self.Ltot2.setFont(textfont)
        self.Quantity.setFont(textfont)
        self.Quantity2.setFont(textfont)
        self.ATotal.setFont(textfont)
        self.CalATotal.setFont(textfont)
        textfont=QFont("Calibri", 15)
        self.Lb.setFont(textfont)
        self.Ld.setFont(textfont)
        self.Lc.setFont(textfont)
        self.Lf.setFont(textfont)
        self.Lq.setFont(textfont)
        self.Ls.setFont(textfont)
        self.Lch.setFont(textfont)        
        self.Calb.setFont(textfont)
        self.Cald.setFont(textfont)
        self.Calc.setFont(textfont)
        self.Calf.setFont(textfont)
        self.Calq.setFont(textfont)
        self.Cals.setFont(textfont)
        self.Calch.setFont(textfont)        
        
        #Allignment of labels and buttons
        self.Lname.move(790,0)
        self.Lmen.move(420,100)
        self.Lmen2.move(810,100)
        self.Ltot.move(710,100)
        self.Ltot2.move(1090,100)
        self.Quantity.move(550,100)
        self.Quantity2.move(950,100)
        self.Lb.move(410,150)
        self.Ld.move(410,200)
        self.Lc.move(410,250)
        self.Lf.move(410,300)
        self.Lq.move(800,175)
        self.Ls.move(800,225)
        self.Lch.move(800,275)
        self.Lb2.move(550,150)
        self.Ld2.move(550,200)
        self.Lc2.move(550,250)
        self.Lf2.move(550,300)
        self.Lq2.move(950,175)
        self.Ls2.move(950,225)
        self.Lch2.move(950,275)
        self.Calb.move(710,150)
        self.Cald.move(710,200)
        self.Calc.move(710,250)
        self.Calf.move(710,300)
        self.Calq.move(1090,175)
        self.Cals.move(1090,225)
        self.Calch.move(1090,275)
        self.CalATotal.move(760,345)
        self.ATotal.move(610,345)
        self.Cal.move(510,350)
        self.Proceed.move(410,350)
        self.Clear.move(460,375)
        self.Cal.clicked.connect(self.Calculation_bl)
        self.Clear.clicked.connect(self.Clearing_bl)
        self.Proceed.clicked.connect(self.proceed_3)
        self.w.setWindowTitle('Burger Lab')
        self.w.setGeometry(100,150,1200,400)
        self.w.show()
        
    #Method for calculation
    def Calculation_bl(self):
        try:
            a=self.Lb2.text()
            b=self.Ld2.text()
            c=self.Lc2.text()
            d=self.Lf2.text()
            e=self.Lq2.text()
            f=self.Ls2.text()
            g=self.Lch2.text()
            if a=='' or b=='' or c=='' or d=='' or f=='' or g=='' or e=='':
                raise Exception("Empty Field")
            else:
                q1 =self.Lb2.text()
                int1= int(q1)*(350)
                self.Calb.setText('Rs'+str(int1))
                q2 =self.Ld2.text()
                int2= int(q2)*(400)
                self.Cald.setText('Rs'+str(int2))
                q3 =self.Lc2.text()
                int3= int(q3)*(250)
                self.Calc.setText('Rs'+str(int3))
                q4 =self.Lf2.text()
                int4= int(q4)*(550)
                self.Calf.setText('Rs'+str(int4))
                q5 =self.Lq2.text()
                int5= int(q5)*(360)
                self.Calq.setText('Rs'+str(int5))
                q6 =self.Ls2.text()
                int6= int(q6)*(200)
                self.Cals.setText('Rs'+str(int6))
                q7 =self.Lch2.text()
                int7= int(q7)*(200)
                self.Calch.setText('Rs'+str(int7))

                q8=int(int1+int2+int3+int4+int5+int6+int7)
                self.CalATotal.setText('Rs'+str(q8))
        except Exception:
                QMessageBox.question(self, 'Error', " Put 0 in Empty Fields", QMessageBox.Yes | QMessageBox.Yes, QMessageBox.Yes)
                print("Exception Raised")            

    #Method to clear the line boxes      
    def Clearing_bl(self):
        self.Lb2.clear()
        self.Ld2.clear()
        self.Lc2.clear()
        self.Lf2.clear()
        self.Lq2.clear()
        self.Ls2.clear()
        self.Lch2.clear()
        self.Calb.clear()
        self.Cald.clear()
        self.Calc.clear()
        self.Calf.clear()
        self.Calq.clear()
        self.Cals.clear()
        self.Calch.clear()
        self.CalATotal.clear()

    #method to call thankyou class
    def proceed_3(self):
        self.tk=Thank_you()
        self.tk.thanks(QtWidgets,QtGui)

    def pizzamax(self,QtWidgets,QtGui):
        self.w = QtWidgets.QWidget()

        #Labels defined
        self.Lname=QtWidgets.QLabel(self.w)
        self.Lmen=QtWidgets.QLabel(self.w)
        self.Lmen2=QtWidgets.QLabel(self.w)
        self.Ltot=QtWidgets.QLabel(self.w)
        self.Ltot2=QtWidgets.QLabel(self.w)
        self.Quantity=QtWidgets.QLabel(self.w)
        self.Quantity2=QtWidgets.QLabel(self.w)
        self.Lb=QtWidgets.QLabel(self.w)
        self.Ld=QtWidgets.QLabel(self.w)
        self.Lc=QtWidgets.QLabel(self.w)
        self.Lf=QtWidgets.QLabel(self.w)
        self.Lq=QtWidgets.QLabel(self.w)
        self.Ls=QtWidgets.QLabel(self.w)
        self.Lch=QtWidgets.QLabel(self.w)

        #Line boxes defined
        self.Lb2=QtWidgets.QLineEdit(self.w)
        self.Ld2=QtWidgets.QLineEdit(self.w)
        self.Lc2=QtWidgets.QLineEdit(self.w)
        self.Lf2=QtWidgets.QLineEdit(self.w)
        self.Lq2=QtWidgets.QLineEdit(self.w)
        self.Ls2=QtWidgets.QLineEdit(self.w)
        self.Lch2=QtWidgets.QLineEdit(self.w)

        #Labels defined
        self.Calb=QtWidgets.QLabel(self.w)
        self.Cald=QtWidgets.QLabel(self.w)
        self.Calc=QtWidgets.QLabel(self.w)
        self.Calf=QtWidgets.QLabel(self.w)
        self.Calq=QtWidgets.QLabel(self.w)
        self.Cals=QtWidgets.QLabel(self.w)
        self.Calch=QtWidgets.QLabel(self.w)

        #Push buttons defined
        self.Cal=QtWidgets.QPushButton(self.w)
        self.Proceed=QtWidgets.QPushButton(self.w)
        self.Clear=QtWidgets.QPushButton(self.w)
        self.ATotal=QtWidgets.QLabel(self.w)
        self.CalATotal=QtWidgets.QLabel(self.w)
        self.pic6=QtWidgets.QLabel(self.w)
        self.pic6.setPixmap(QtGui.QPixmap('000055216_Pizza-Max'))

        
        #Labels and buttons set TEXT
        self.Lname.setText('MENU')
        self.Lmen.setText('Items')
        self.Lmen2.setText("Items")
        self.Ltot.setText('Price')
        self.Ltot2.setText("Price")
        self.Quantity.setText('Quantity')
        self.Quantity2.setText("Quantity")
        self.Lb.setText('Chicken Fajita')
        self.Ld.setText('Creamy Max')
        self.Lc.setText('Cheese Max')
        self.Lf.setText('Chicken Pasta')
        self.Lq.setText('Garlic Bread ')
        self.Ls.setText('Malai Boti')
        self.Lch.setText('Afghani Tikka')
        self.ATotal.setText('Final total:')
        self.Cal.setText('Calculation')
        self.Proceed.setText('Proceed')
        self.Clear.setText('Clear')
        self.CalATotal.setText('                             ')
        self.Calb.setText('                               ')
        self.Cald.setText('                               ')
        self.Calc.setText('                               ')
        self.Calf.setText('                               ')
        self.Calq.setText('                               ')
        self.Cals.setText('                               ')
        self.Calch.setText('                               ')        
        
        #font size of TEXT    
        textfont=QFont("Impact", 26)
        self.Lname.setFont(textfont)
        textfont=QFont("Times", 20)
        self.Lmen.setFont(textfont)
        self.Lmen2.setFont(textfont)
        self.Ltot.setFont(textfont)
        self.Ltot2.setFont(textfont)
        self.Quantity.setFont(textfont)
        self.Quantity2.setFont(textfont)
        self.ATotal.setFont(textfont)
        self.CalATotal.setFont(textfont)
        textfont=QFont("Calibri", 15)
        self.Lb.setFont(textfont)
        self.Ld.setFont(textfont)
        self.Lc.setFont(textfont)
        self.Lf.setFont(textfont)
        self.Lq.setFont(textfont)
        self.Ls.setFont(textfont)
        self.Lch.setFont(textfont)        
        self.Calb.setFont(textfont)
        self.Cald.setFont(textfont)
        self.Calc.setFont(textfont)
        self.Calf.setFont(textfont)
        self.Calq.setFont(textfont)
        self.Cals.setFont(textfont)
        self.Calch.setFont(textfont)        
        
        #Allignment of labels and buttons
        self.Lname.move(790,0)
        self.Lmen.move(420,100)
        self.Lmen2.move(810,100)
        self.Ltot.move(710,100)
        self.Ltot2.move(1090,100)
        self.Quantity.move(550,100)
        self.Quantity2.move(950,100)
        self.Lb.move(410,150)
        self.Ld.move(410,200)
        self.Lc.move(410,250)
        self.Lf.move(410,300)
        self.Lq.move(810,175)
        self.Ls.move(810,225)
        self.Lch.move(810,275)
        self.Lb2.move(550,150)
        self.Ld2.move(550,200)
        self.Lc2.move(550,250)
        self.Lf2.move(550,300)
        self.Lq2.move(950,175)
        self.Ls2.move(950,225)
        self.Lch2.move(950,275)
        self.Calb.move(710,150)
        self.Cald.move(710,200)
        self.Calc.move(710,250)
        self.Calf.move(710,300)
        self.Calq.move(1090,175)
        self.Cals.move(1090,225)
        self.Calch.move(1090,275)
        self.CalATotal.move(760,345)
        self.ATotal.move(610,345)
        self.Cal.move(510,350)
        self.Proceed.move(410,350)
        self.Clear.move(460,375)
        self.Cal.clicked.connect(self.Calculation_pm)
        self.Clear.clicked.connect(self.Clearing_pm)
        self.Proceed.clicked.connect(self.proceed_4)
        self.w.setWindowTitle('Pizza Max')
        self.w.setGeometry(100,150,1200,400)
        self.w.show()

    #Method for calculation    
    def Calculation_pm(self):
        try:
            a=self.Lb2.text()
            b=self.Ld2.text()
            c=self.Lc2.text()
            d=self.Lf2.text()
            e=self.Lq2.text()
            f=self.Ls2.text()
            g=self.Lch2.text()
            if a=='' or b=='' or c=='' or d=='' or f=='' or g=='' or e=='':
                raise Exception("Empty Field")
            else:

                q1 =self.Lb2.text()
                int1= int(q1)*(700)
                self.Calb.setText('Rs'+str(int1))
                q2 =self.Ld2.text()
                int2= int(q2)*(900)
                self.Cald.setText('Rs'+str(int2))
                q3 =self.Lc2.text()
                int3= int(q3)*(850)
                self.Calc.setText('Rs'+str(int3))
                q4 =self.Lf2.text()
                int4= int(q4)*(400)
                self.Calf.setText('Rs'+str(int4))
                q5 =self.Lq2.text()
                int5= int(q5)*(300)
                self.Calq.setText('Rs'+str(int5))
                q6 =self.Ls2.text()
                int6= int(q6)*(200)
                self.Cals.setText('Rs'+str(int6))
                q7 =self.Lch2.text()
                int7= int(q7)*(1100)
                self.Calch.setText('Rs'+str(int7))

                q8=int(int1+int2+int3+int4+int5+int6+int7)
                self.CalATotal.setText('Rs'+str(q8))
        except Exception:
                QMessageBox.question(self, 'Error', " Put 0 in Empty Fields", QMessageBox.Yes | QMessageBox.Yes, QMessageBox.Yes)
                print("Exception Raised")            

    #Clear function that will clear all the line boxes    
    def Clearing_pm(self):
        self.Lb2.clear()
        self.Ld2.clear()
        self.Lc2.clear()
        self.Lf2.clear()
        self.Lq2.clear()
        self.Ls2.clear()
        self.Lch2.clear()
        self.Calb.clear()
        self.Cald.clear()
        self.Calc.clear()
        self.Calf.clear()
        self.Calq.clear()
        self.Cals.clear()
        self.Calch.clear()
        self.CalATotal.clear()

    def proceed_4(self):
        self.tk=Thank_you()
        self.tk.thanks(QtWidgets,QtGui)

    def del_frio(self,QtWidgets,QtGui):
         self.w = QtWidgets.QWidget()

         #Push buttons defined
         self.Proceed=QtWidgets.QPushButton(self.w)
         self.Clear=QtWidgets.QPushButton(self.w)
         self.Cal=QtWidgets.QPushButton(self.w)

         #Labels defined
         self.Lcoolingpunch=QtWidgets.QLabel(self.w)
         self.Langelmist=QtWidgets.QLabel(self.w)
         self.Llemonmintglacier=QtWidgets.QLabel(self.w)
         self.Lbluecolada=QtWidgets.QLabel(self.w)
         self.Lname=QtWidgets.QLabel(self.w)
         self.Lmen=QtWidgets.QLabel(self.w)
         self.total=QtWidgets.QLabel(self.w)
         self.scoops=QtWidgets.QLabel(self.w)
         self.Calcoolingpunch=QtWidgets.QLabel(self.w)
         self.Calangelmist=QtWidgets.QLabel(self.w)
         self.Callemonmintglacier=QtWidgets.QLabel(self.w)
         self.Calbluecolada=QtWidgets.QLabel(self.w)
         self.ATotal=QtWidgets.QLabel(self.w)
         self.CalATotal=QtWidgets.QLabel(self.w)

         #Line boxes defined
         self.Lcoolingpunch2=QtWidgets.QLineEdit(self.w)
         self.Langelmist2=QtWidgets.QLineEdit(self.w)
         self.Llemonmintglacier2=QtWidgets.QLineEdit(self.w)
         self.Lbluecolada2=QtWidgets.QLineEdit(self.w)
         self.pic5=QtWidgets.QLabel(self.w)
         self.pic5.setPixmap(QtGui.QPixmap('116_Del-Frio1'))

         #set TEXT for buttons and labels
         self.Lname.setText('MENU')
         self.Lmen.setText('Flavours')
         self.Lcoolingpunch.setText('Coffee Classic')
         self.Langelmist.setText('Strawberry Cheese Cake')
         self.Llemonmintglacier.setText('Chocolate Fludge')
         self.Lbluecolada.setText('Mud Slide')
         self.Proceed.setText('Proceed')
         self.Clear.setText('Clear')
         self.Cal.setText('Calculate')
         self.Calcoolingpunch.setText('             ')
         self.Calangelmist.setText('              ')
         self.Callemonmintglacier.setText('               ')
         self.Calbluecolada.setText('            ')
         self.CalATotal.setText('               ')
         self.total.setText('Total Amount')
         self.scoops.setText('Scoops')
         self.ATotal.setText('Final Total: ')
 
         #font size of Labels 
         textfont=QFont("Impact", 26)
         self.Lname.setFont(textfont)
         textfont=QFont("Times", 20)
         self.Lmen.setFont(textfont)
         textfont=QFont("Times", 20)
         self.scoops.setFont(textfont)
         self.total.setFont(textfont)
         self.ATotal.setFont(textfont)
         self.CalATotal.setFont(textfont)
         textfont=QFont("Calibri", 15)
         self.Lcoolingpunch.setFont(textfont)
         self.Langelmist.setFont(textfont)
         self.Llemonmintglacier.setFont(textfont)
         self.Lbluecolada.setFont(textfont)
         self.Calcoolingpunch.setFont(textfont)
         self.Calangelmist.setFont(textfont)
         self.Callemonmintglacier.setFont(textfont)
         self.Calbluecolada.setFont(textfont)

         #Allignment of labels and buttons
         self.Lname.move(590,0)
         self.Lmen.move(420,100)
         self.Lcoolingpunch.move(410,150)
         self.Langelmist.move(410,200)
         self.Llemonmintglacier.move(410,250)
         self.Lbluecolada.move(410,300)
         self.Lcoolingpunch2.move(570,150)
         self.Langelmist2.move(570,200)
         self.Llemonmintglacier2.move(570,250)
         self.Lbluecolada2.move(570,300)
         self.Proceed.move(410,350)
         self.Clear.move(460,375)
         self.Cal.move(510,350)
         self.scoops.move(570,100)
         self.total.move(710,100)
         self.Calcoolingpunch.move(710,148)
         self.Calangelmist.move(710,198)
         self.Callemonmintglacier.move(710,248)
         self.Calbluecolada.move(710,298)
         self.CalATotal.move(760,345)
         self.ATotal.move(610,345)
         self.Cal.clicked.connect(self.Calculation_df)
         self.Clear.clicked.connect(self.Clearing_df)
         self.Proceed.clicked.connect(self.proceed_5)
         self.w.setGeometry(290,150,890,400)
         self.w.setWindowTitle('Del Frio')
         self.w.show()

    #This method will gives us calculation
    def Calculation_df(self):
        try:
            a=self.Lcoolingpunch2.text()
            b=self.Langelmist2.text()
            c=self.Llemonmintglacier2.text()
            d=self.Lbluecolada2.text()
            if a=='' or b=='' or c=='' or d=='':
                raise Exception("Empty Field")
            else:
                q1 =self.Lcoolingpunch2.text()
                int1= int(q1)*(140)
                self.Calcoolingpunch.setText('Rs'+str(int1))
                q2 =self.Langelmist2.text()
                int2= int(q2)*(180)
                self.Calangelmist.setText('Rs'+str(int2))
                q3 =self.Llemonmintglacier2.text()
                int3= int(q3)*(160)
                self.Callemonmintglacier.setText('Rs'+str(int3))
                q4 =self.Lbluecolada2.text()
                int4= int(q4)*(150)
                self.Calbluecolada.setText('Rs'+str(int4))
                q5=int(int1+int2+int3+int4)
                self.CalATotal.setText('Rs'+str(q5))
        
        except Exception:
                QMessageBox.question(self, 'Error', " Put 0 in Empty Fields", QMessageBox.Yes | QMessageBox.Yes, QMessageBox.Yes)
                print("Exception Raised")            


    #A method that will clear all the line boxes
    def Clearing_df(self):             
          self.Calcoolingpunch.clear()
          self.Calangelmist.clear()
          self.Callemonmintglacier.clear()
          self.Calbluecolada.clear()
          self.Lcoolingpunch2.clear()
          self.Langelmist2.clear()
          self.Llemonmintglacier2.clear()
          self.Lbluecolada2.clear()
          self.CalATotal.clear()
          self.w.show()
          
    def proceed_5(self):
        self.tk=Thank_you()
        self.tk.thanks(QtWidgets,QtGui)
    
    def shaheen_shinwari(self,QtWidgets,QtGui):
        self.w = QtWidgets.QWidget()

        #Labels defined
        self.Lname=QtWidgets.QLabel(self.w)
        self.Lmen=QtWidgets.QLabel(self.w)
        self.Lmen2=QtWidgets.QLabel(self.w)
        self.Ltot=QtWidgets.QLabel(self.w)
        self.Ltot2=QtWidgets.QLabel(self.w)
        self.Quantity=QtWidgets.QLabel(self.w)
        self.Quantity2=QtWidgets.QLabel(self.w)
        self.Lb=QtWidgets.QLabel(self.w)
        self.Ld=QtWidgets.QLabel(self.w)
        self.Lc=QtWidgets.QLabel(self.w)
        self.Lf=QtWidgets.QLabel(self.w)
        self.Lq=QtWidgets.QLabel(self.w)
        self.Ls=QtWidgets.QLabel(self.w)
        self.Lch=QtWidgets.QLabel(self.w)

        #Line boxes defined
        self.Lb2=QtWidgets.QLineEdit(self.w)
        self.Ld2=QtWidgets.QLineEdit(self.w)
        self.Lc2=QtWidgets.QLineEdit(self.w)
        self.Lf2=QtWidgets.QLineEdit(self.w)
        self.Lq2=QtWidgets.QLineEdit(self.w)
        self.Ls2=QtWidgets.QLineEdit(self.w)
        self.Lch2=QtWidgets.QLineEdit(self.w)

        #Labels defined
        self.Calb=QtWidgets.QLabel(self.w)
        self.Cald=QtWidgets.QLabel(self.w)
        self.Calc=QtWidgets.QLabel(self.w)
        self.Calf=QtWidgets.QLabel(self.w)
        self.Calq=QtWidgets.QLabel(self.w)
        self.Cals=QtWidgets.QLabel(self.w)
        self.Calch=QtWidgets.QLabel(self.w)
        self.Cal=QtWidgets.QPushButton(self.w)
        self.Proceed=QtWidgets.QPushButton(self.w)
        self.Clear=QtWidgets.QPushButton(self.w)
        self.ATotal=QtWidgets.QLabel(self.w)
        self.CalATotal=QtWidgets.QLabel(self.w)
        self.pic6=QtWidgets.QLabel(self.w)
        self.pic6.setPixmap(QtGui.QPixmap('17352163_1879669988922951_5219865013355972827_n'))

        #set TEXT for labels and buttons
        self.Lname.setText('MENU')
        self.Lmen.setText('Items')
        self.Lmen2.setText("Items")
        self.Ltot.setText('Price')
        self.Ltot2.setText("Price")
        self.Quantity.setText('Quantity')
        self.Quantity2.setText("Quantity")
        self.Lb.setText('Koila Karahi')
        self.Ld.setText('Chicken Handi')
        self.Lc.setText('Malai Boti')
        self.Lf.setText('Afghani Tikka')
        self.Lq.setText('Brain Masala')
        self.Ls.setText('Mutton Chops')
        self.Lch.setText('Chicken Wings')
        self.ATotal.setText('Final total:')
        self.Cal.setText('Calculation')
        self.Proceed.setText('Proceed')
        self.Clear.setText('Clear')
        self.CalATotal.setText('                             ')
        self.Calb.setText('                               ')
        self.Cald.setText('                               ')
        self.Calc.setText('                               ')
        self.Calf.setText('                               ')
        self.Calq.setText('                               ')
        self.Cals.setText('                               ')
        self.Calch.setText('                               ')        
        
        #Font size for labels     
        textfont=QFont("Impact", 26)
        self.Lname.setFont(textfont)
        textfont=QFont("Times", 20)
        self.Lmen.setFont(textfont)
        self.Lmen2.setFont(textfont)
        self.Ltot.setFont(textfont)
        self.Ltot2.setFont(textfont)
        self.Quantity.setFont(textfont)
        self.Quantity2.setFont(textfont)
        self.ATotal.setFont(textfont)
        self.CalATotal.setFont(textfont)
        textfont=QFont("Calibri", 15)
        self.Lb.setFont(textfont)
        self.Ld.setFont(textfont)
        self.Lc.setFont(textfont)
        self.Lf.setFont(textfont)
        self.Lq.setFont(textfont)
        self.Ls.setFont(textfont)
        self.Lch.setFont(textfont)        
        self.Calb.setFont(textfont)
        self.Cald.setFont(textfont)
        self.Calc.setFont(textfont)
        self.Calf.setFont(textfont)
        self.Calq.setFont(textfont)
        self.Cals.setFont(textfont)
        self.Calch.setFont(textfont)        
        
        #Allignment of labels and buttons
        self.Lname.move(790,0)
        self.Lmen.move(420,100)
        self.Lmen2.move(810,100)
        self.Ltot.move(710,100)
        self.Ltot2.move(1090,100)
        self.Quantity.move(550,100)
        self.Quantity2.move(950,100)
        self.Lb.move(410,150)
        self.Ld.move(410,200)
        self.Lc.move(410,250)
        self.Lf.move(410,300)
        self.Lq.move(810,175)
        self.Ls.move(810,225)
        self.Lch.move(810,275)
        self.Lb2.move(550,150)
        self.Ld2.move(550,200)
        self.Lc2.move(550,250)
        self.Lf2.move(550,300)
        self.Lq2.move(950,175)
        self.Ls2.move(950,225)
        self.Lch2.move(950,275)
        self.Calb.move(710,150)
        self.Cald.move(710,200)
        self.Calc.move(710,250)
        self.Calf.move(710,300)
        self.Calq.move(1090,175)
        self.Cals.move(1090,225)
        self.Calch.move(1090,275)
        self.CalATotal.move(760,345)
        self.ATotal.move(610,345)
        self.Cal.move(510,350)
        self.Proceed.move(410,350)
        self.Clear.move(460,375)
        self.Cal.clicked.connect(self.Calculation_s)
        self.Clear.clicked.connect(self.Clearing_ss)
        self.Proceed.clicked.connect(self.proceed_6)
        self.w.setWindowTitle('Shaheen Shinwari')
        self.w.setGeometry(100,150,1200,400)
        self.w.show()

    #Method for calculation
    def Calculation_s(self):
        try:
            a=self.Lb2.text()
            b=self.Ld2.text()
            c=self.Lc2.text()
            d=self.Lf2.text()
            e=self.Lq2.text()
            f=self.Ls2.text()
            g=self.Lch2.text()
            if a=='' or b=='' or c=='' or d=='' or f=='' or g=='' or e=='':
                raise Exception("Empty Field")
            else:

                q1 =self.Lb2.text()
                int1= int(q1)*(1300)
                self.Calb.setText('Rs'+str(int1))
                q2 =self.Ld2.text()
                int2= int(q2)*(1200)
                self.Cald.setText('Rs'+str(int2))
                q3 =self.Lc2.text()
                int3= int(q3)*(1350)
                self.Calc.setText('Rs'+str(int3))
                q4 =self.Lf2.text()
                int4= int(q4)*(1400)
                self.Calf.setText('Rs'+str(int4))
                q5 =self.Lq2.text()
                int5= int(q5)*(1100)
                self.Calq.setText('Rs'+str(int5))
                q6 =self.Ls2.text()
                int6= int(q6)*(1200)
                self.Cals.setText('Rs'+str(int6))
                q7 =self.Lch2.text()
                int7= int(q7)*(500)
                self.Calch.setText('Rs'+str(int7))

                q8=int(int1+int2+int3+int4+int5+int6+int7)
                self.CalATotal.setText('Rs'+str(q8))
        except Exception:
                QMessageBox.question(self, 'Error', " Put 0 in Empty Fields", QMessageBox.Yes | QMessageBox.Yes, QMessageBox.Yes)
                print("Exception Raised")            

    #A method that will clear all the line boxes   
    def Clearing_ss(self):
        self.Lb2.clear()
        self.Ld2.clear()
        self.Lc2.clear()
        self.Lf2.clear()
        self.Lq2.clear()
        self.Ls2.clear()
        self.Lch2.clear()
        self.Calb.clear()
        self.Cald.clear()
        self.Calc.clear()
        self.Calf.clear()
        self.Calq.clear()
        self.Cals.clear()
        self.Calch.clear()
        self.CalATotal.clear()

    def proceed_6(self):
        self.tk=Thank_you()
        self.tk.thanks(QtWidgets,QtGui)




